trigger:
- master

stages:
  - stage: 'here we are building the app'
    jobs:
    - job: 'build-mvc-job'
      steps:
      - task: DotNetCoreCLI@2
        displayName: 'now building'
        inputs:
          command: build
          arguments: '-c Release -o $(Build.ArtifactStagingDirectory)'
      
      - script: |
         echo '-----------------build files--------------------'
         echo'dir $(Build.ArtifactStagingDirectory)'
         

